import { Brand } from "@/types/brand";

const brandData: Brand[] = [
  {
    id: 1,
    name: "Seasons Foods",
    href: "https://www.seasonsgroup.com.pk/index.html",
    image: "/images/brand/Seasons-Foods.png",
    imageLight: "/images/brand/Seasons-Foods.png",
  },
  {
    id: 2,
    name: "Menu Chicken",
    href: "https://menu.com.pk/",
    image: "/images/brand/Menu.png",
    imageLight: "/images/brand/Menu.png",
  },
  {
    id: 3,
    name: "Akbari Polymers",
    href: "https://www.akbarigroup.pk/",
    image: "/images/brand/Akbari Polymers.png",
    imageLight: "/images/brand/Akbari Polymers.png",
    
  },
  {
    id: 4,
    name: "Yutian Chemicals Pvt Ltd.",
    href: "https://yutianchemicals.com/",
    image: "/images/brand/ytLogo.png",
    imageLight: "/images/brand/ytLogo.png",
  },
  {
    id: 5,
    name: "National Flour Mills",
    href: "https://www.nationalflourmill.com/",
    image: "/images/brand/national.png",
    imageLight: "/images/brand/national.png",
  },
  {
    id: 6,
    name: "Universal Unisoft",
    href: "#",
    image: "/images/brand/universalLogo.png",
    imageLight: "/images/brand/universalLogo.png",
  },
  {
    id: 7,
    name: "Hyundai Premium",
    href: "https://hyundaipremium.com/",
    image: "/images/brand/hyundai premium.jpg",
    imageLight: "/images/brand/hyundai premium.jpg",
  },
  {
    id: 8,
    name: "Akbari Enginnering",
    href: "https://akbariengineering.com/",
    image: "/images/brand/Akbari Enginnering.png",
    imageLight: "/images/brand/Akbari Enginnering.png",
  },
  {
    id: 9,
    name: "Sunhance",
    href: "https://www.sunhance.pk/",
    image: "/images/brand/sunhance.jpg",
    imageLight: "/images/brand/sunhance.jpg",
  },
  {
    id: 10,
    name: "Construir Bien",
    href: "https://www.construirbien.com/",
    image: "/images/brand/CB.png",
    imageLight: "/images/brand/CB.png",
  },
  {
    id: 11,
    name: "Descon",
    href: "https://www.descon.com/",
    image: "/images/brand/Descon.jpg",
    imageLight: "/images/brand/Descon.jpg",
  },
  {
    id: 12,
    name: "Atlas Power",
    href: "https://apl.atlas.pk/",
    image: "/images/brand/apllogo.jpg",
    imageLight: "/images/brand/apllogo.jpg",
  },
  {
    id: 13,
    name: "Gulf Oil",
    href: "https://www.gulfoilltd.com/",
    image: "/images/brand/gulf.png",
    imageLight: "/images/brand/gulf.png",
  },
  {
    id: 14,
    name: "Harness",
    href: "#",
    image: "/images/brand/harness.png",
    imageLight: "/images/brand/harness.png",
  },
  {
    id: 15,
    name: "Tetra Pak",
    href: "https://www.tetrapak.com/en-pk",
    image: "/images/brand/tetra-pak.jpg",
    imageLight: "/images/brand/tetra-pak.jpg",
  },
  {
    id: 16,
    name: "Chawala Aluminium",
    href: "https://www.chawlagroup.com.pk/",
    image: "/images/brand/chawla.png",
    imageLight: "/images/brand/chawla.png",
  },
  {
    id: 17,
    name: "Engro Foods",
    href: "https://www.engro.com/",
    image: "/images/brand/engro foods.png",
    imageLight: "/images/brand/engro foods.png",
  },
  {
    id: 18,
    name: "Zenith Associates",
    href: "https://zenith.pk/services",
    image: "/images/brand/zenith.png",
    imageLight: "/images/brand/zenith.png",
  },
  {
    id: 19,
    name: "Beta Pipes",
    href: "https://betapipes.com.pk/",
    image: "/images/brand/Beta Pipes.png",
    imageLight: "/images/brand/Beta Pipes.png",
  },
];

export default brandData;
